### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by dmitryfedorov292** [marcofugaro/codrops-texture-projection#1]
I did npm install and did npm start but it doesn't work.
I am using Windows 10, Visual Studio Code
PS E:\00Work\OurSites\modules\Threejs Noise\codrops-texture-projection-master> npm start

> @ prestart E:\00Work\OurSites\modules\Threejs Noise\codrops-texture-projection-master
> npm run clean

> @ clean E:\00Work\OurSites\modules\Threejs Noise\codrops-texture-projection-master
> rimraf ./app*.js

> @ start E:\00Work\OurSites\modules\Threejs Noise\codrops-texture-projection-master
> NODE_ENV=development webpack-dev-server

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `NODE_ENV=development webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mainstar\AppData\Roaming\npm-cache\_logs\2020-04-05T16_01_46_426Z-debug.log

**Comment by marcofugaro** [comment]
Hey @dmitryfedorov292 my bad, I didn't test on a windows machine. Try replacing

```
"start": "NODE_ENV=development webpack-dev-server",
```

```
"start": "set NODE_ENV=development webpack-dev-server",
```

in the `package.json`

**Comment by dmitryfedorov292** [comment]
It's working for me! I just changed scripts to
    "start": "SET NODE_ENV=development & webpack-dev-server",
    "build": "SET NODE_ENV=production & webpack",
But I have found better solution.
That is to use npm cross-env. You can use any platform.

**Comment by marcofugaro** [comment]
Thank you for the tip!
